### ISSUE TITLE
The definition of RFE in the pKa challenge

### ISSUE THREAD

**Issue by xiki-tempula** [samplchallenges/SAMPL8#28]
Sorry for this naive question and this is the first time that I participate in this challenge. I think I have read all the instructions but I might have missed this. I wonder how is the RFE in the pKa challenge being defined?

I think there are two levels of defining relative free energy.

The free energy of each tautomer with respect to the tautomer with the same charge. Is this the reason that the charge of the molecule is included in the submission script?

Or 

The free energy of each tautomer with respect to the tautomer with all different charges, so people have the additional pain of adding the free energy of the proton.

Thank you.

**Comment by davidlmobley** [comment]
Hi, you might check out the SAMPL7 pKa overview paper for more on how the analysis and concepts work, but basically we're looking for the reaction free energy away from the reference microstate (whether or not that corresponds to a physical reaction). If it's a transition which involves a change in formal charge, that would include the free energy of giving up or adding a proton, so in that sense it includes the proton free energy -- but it may not be something where you would need to separately compute the proton free energy (see here: https://github.com/samplchallenges/SAMPL8/blob/master/physical_properties/pKa/pKa_challenge_instructions.md)

Basically, these free energies for a reaction, so for a reaction HA -> H + A (where HA corresponds to the reference microstate) this free energy would directly relate to the pKa, and would be related to the ratio of products (dissociated form) to reactants (associated form). 

If you're talking about tautomers of the same formal charge, you'd be dealing with the relative populations of different tautomers (and the associated free energy), e.g. T1 -> T2 where T1 is the reference microstate and T2 is another microstate of the same formal charge, and you'd be estimating the free energy of that reaction.

I hope that helps; if not, please ask further; it may be helpful if you explain what you're computing and how, as differnet communities tend to have somewhat different ways to think about these phenomena.

**Comment by xiki-tempula** [comment]
Thanks and I think I understand the term now.
