### ISSUE TITLE
What pH value for LogD challenge

### ISSUE THREAD

**Issue by IamDavyG** [samplchallenges/SAMPL8#38]
I'm in the final stages of making a submission into the LogD challenge but I would like to ask what pH value should the LogD be calculated at? I just assumed pH 7.4 all along because the earlier text mentioned it would be like SAMPL7 which used LogD_7.4.

**Comment by davidlmobley** [comment]
This is in the instructions on the repo, some are pH 8 and others pH 3. Sorry to be brief but I'm about to go offline for a number of hours and can't retrieve the link right now.

**Comment by davidlmobley** [comment]
Actually that's probably pH 4 rather than 3. See instructions (should be in the physical properties instructions - a recent update).

**Comment by IamDavyG** [comment]
Alright, I assume it's pH 4 but I put in pH 3 in my submission just in case

**Comment by davidlmobley** [comment]
For the record, it's in this file -- https://github.com/samplchallenges/SAMPL8/blob/master/physical_properties/README.md

"Update 2021-08-20: pH 8 was used for SAMPL8-1, 3, 5 and 6; all other compounds were done at pH 3."
